/**
 * Public disclosure of the AI models behind NeotypeLab generation.
 *
 * Single source for the Acceptable Use Policy, the Privacy Policy, and the
 * in-product provider notes. When the image or text route changes provider,
 * update this file in the same change so the disclosure never drifts.
 */
export const aiModelDisclosure = {
  image: {
    model: "OpenAI GPT Image (gpt-image-2.5)",
    /** Version-free name for surfaces that should not change on a model upgrade (e.g. Pricing). */
    family: "OpenAI GPT Image",
    developer: "OpenAI",
    servedVia: "Cloudflare Workers AI",
    uses: "HD renders and other preview images",
  },
  text: {
    model: "Google Gemini",
    developer: "Google",
    servedVia: "the Google Gemini API",
    uses: "Custom Style interpretation, palette and paint plans, and repaint specifications",
  },
  safety: {
    provider: "Waffo",
    service: "Waffo content safety screening",
  },
} as const;

export const imageProviderNote = `Images are generated by ${aiModelDisclosure.image.model}, served through ${aiModelDisclosure.image.servedVia}.`;
export const textProviderNote = `Text is generated by ${aiModelDisclosure.text.model} via ${aiModelDisclosure.text.servedVia}.`;
export const safetyScreeningNote = "Prompts are screened for safety before generation.";
