import type { SystemStateDefinition } from "./systemStateTypes";

export const systemStates = {
  notFound: {
    code: "404",
    archive: "Route archive / N°404",
    headline: "Route\nnot found",
    message: [
      "This record does not exist in the NeotypeLab archive.",
      "It may have been moved, renamed, or removed.",
    ],
    signal: "missing",
    signalLabel: "Route / Missing",
    purpose: "error",
    context: "NeotypeLab system",
  },
  serverError: {
    code: "500",
    archive: "System archive / N°500",
    headline: "Render\ninterrupted",
    message: [
      "NeotypeLab could not complete this route.",
      "The record is still in the archive. Retry the request, or return to a known path.",
    ],
    signal: "interrupted",
    signalLabel: "System / Error",
    purpose: "fault",
    context: "NeotypeLab system",
  },
  forbidden: {
    code: "403",
    archive: "Access archive / N°403",
    headline: "Restricted\nrecord",
    message: [
      "This record is private to another operator.",
      "Return to your library, or open a public case instead.",
    ],
    signal: "locked",
    signalLabel: "Access / Private",
    purpose: "error",
    context: "NeotypeLab system",
  },
  authWorkspace: {
    code: "AUTH",
    archive: "Access / Private workspace",
    headline: "Your workspace\nis private.",
    message: [
      "Sign in to access your prototypes, paint plans, renders and saved builds.",
    ],
    signal: "locked",
    signalLabel: "Access / Locked",
    purpose: "access",
    context: "Private archive",
  },
  authCreate: {
    code: "AUTH",
    archive: "Create / Session required",
    headline: "Start a\nprototype record.",
    message: [
      "NeotypeLab uses structured inputs instead of open-ended prompts.",
      "Sign in to use your credit balance, then choose a kit, define a direction, and generate a working record.",
    ],
    signal: "locked",
    signalLabel: "Access / Locked",
    purpose: "access",
    context: "Create console",
  },
  authStudio: {
    code: "AUTH",
    archive: "Studio / Private resources",
    headline: "Your workspace\nis private.",
    message: [
      "Sign in to open production resources, spray plans, paint inventory, credits and orders.",
    ],
    signal: "locked",
    signalLabel: "Access / Locked",
    purpose: "access",
    context: "Studio",
  },
  authRecord: {
    code: "AUTH",
    archive: "Access / Private record",
    headline: "This record\nis private.",
    message: [
      "Work details, paint plans and build resources stay with their owner.",
      "Sign in to open the record, or return to the public archive.",
    ],
    signal: "locked",
    signalLabel: "Access / Private",
    purpose: "access",
    context: "Prototype record",
  },
  authFeedback: {
    code: "AUTH",
    archive: "Feedback / Session required",
    headline: "Session\nrequired",
    message: [
      "Sign in to attach prototype context and follow each report from received to resolved.",
    ],
    signal: "locked",
    signalLabel: "Access / Locked",
    purpose: "access",
    context: "Feedback archive",
  },
  authAdmin: {
    code: "AUTH",
    archive: "Platform / Restricted",
    headline: "Restricted\nrecord",
    message: [
      "The admin console is limited to platform operators.",
      "Sign in with a cleared account to continue.",
    ],
    signal: "locked",
    signalLabel: "Access / Private",
    purpose: "access",
    context: "NeotypeLab admin",
  },
  emptyLibrary: {
    code: "000",
    archive: "Library / First record",
    headline: "Your archive\nstarts here.",
    message: [
      "Concepts become working records: color systems, paint plans, renders and build resources.",
    ],
    signal: "empty",
    signalLabel: "Archive / Empty",
    purpose: "onboarding",
    context: "Prototype library",
    steps: [
      { index: "01", label: "Choose a kit" },
      { index: "02", label: "Define a direction" },
      { index: "03", label: "Generate your prototype" },
    ],
  },
  emptyCollection: {
    code: "000",
    archive: "Library / Collection",
    headline: "No saved\nrecords yet",
    message: [
      "Save a public build from Showcase to keep it here as a reference archive.",
    ],
    signal: "empty",
    signalLabel: "Archive / Empty",
    purpose: "empty",
    context: "Collection",
  },
  emptyShowcase: {
    code: "000",
    archive: "Showcase / Public archive",
    headline: "Nothing\npublished yet",
    message: [
      "Public cases will appear here after a prototype is moved from the private library onto the showcase.",
    ],
    signal: "empty",
    signalLabel: "Public / Empty",
    purpose: "empty",
    context: "Public archive",
  },
  emptyQuery: {
    code: "0 MATCHES",
    archive: "Query / Empty",
    headline: "No matching\nrecords",
    message: [
      "Nothing in this archive matches the current filters.",
      "Clear the query to return to the full set.",
    ],
    signal: "query",
    signalLabel: "Query / Empty",
    purpose: "empty",
    context: "Discovery",
  },
  generationFailed: {
    code: "FAILED",
    archive: "Generation record / Interrupted",
    headline: "Render did\nnot complete",
    message: [
      "The preview renderer stopped before a valid image was stored.",
      "Credits for this job are returned when the interruption is refunded.",
    ],
    signal: "failed",
    signalLabel: "Job / Failed",
    purpose: "fault",
    context: "Generation",
  },
  sessionLoading: {
    code: "SYNC",
    archive: "Session / Opening",
    headline: "Opening\nthe archive.",
    message: [
      "Clerk is present and Convex is negotiating the authenticated viewer token.",
    ],
    signal: "loading",
    signalLabel: "System / Sync",
    purpose: "progress",
    context: "NeotypeLab system",
  },
  libraryLoading: {
    code: "SYNC",
    archive: "Library / Indexing",
    headline: "Indexing\nprototype records.",
    message: [
      "Saved builds, render jobs and storage ledgers are being resolved for this operator.",
    ],
    signal: "loading",
    signalLabel: "Archive / Sync",
    purpose: "progress",
    context: "Prototype library",
  },
  exploreLoading: {
    code: "SYNC",
    archive: "Explore / Indexing",
    headline: "Opening\nthe public archive.",
    message: [
      "Published prototypes are being resolved for this view.",
    ],
    signal: "loading",
    signalLabel: "Archive / Sync",
    purpose: "progress",
    context: "Public archive",
  },
  showcaseLoading: {
    code: "SYNC",
    archive: "Showcase / Indexing",
    headline: "Opening\nthe public archive.",
    message: [
      "Selected works, collections and recent publications are being resolved.",
    ],
    signal: "loading",
    signalLabel: "Archive / Sync",
    purpose: "progress",
    context: "Public archive",
  },
  recordMissing: {
    code: "404",
    archive: "Library / Missing record",
    headline: "Record\nnot found",
    message: [
      "This work is unavailable in your library.",
      "It may have been removed, or it belongs to another operator.",
    ],
    signal: "missing",
    signalLabel: "Route / Missing",
    purpose: "error",
    context: "Prototype library",
  },
} as const satisfies Record<string, SystemStateDefinition>;

export type SystemStatePreset = keyof typeof systemStates;
