/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TRouteImport } from './routes/t'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TLibraryRouteImport } from './routes/t_.library'
import { Route as PrototypeConceptIdRouteImport } from './routes/prototype.$conceptId'
import { Route as PilotHandleRouteImport } from './routes/pilot.$handle'

const TRoute = TRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TLibraryRoute = TLibraryRouteImport.update({
  id: '/t_/library',
  path: '/t/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeConceptIdRoute = PrototypeConceptIdRouteImport.update({
  id: '/prototype/$conceptId',
  path: '/prototype/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotHandleRoute = PilotHandleRouteImport.update({
  id: '/pilot/$handle',
  path: '/pilot/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRoute
  '/t': typeof TRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/t/library': typeof TLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRoute
  '/t': typeof TRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/t/library': typeof TLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRoute
  '/t': typeof TRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/t_/library': typeof TLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/showcase'
    | '/t'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/t/library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/showcase'
    | '/t'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/t/library'
  id:
    | '__root__'
    | '/'
    | '/showcase'
    | '/t'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/t_/library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TRoute: typeof TRoute
  PilotHandleRoute: typeof PilotHandleRoute
  PrototypeConceptIdRoute: typeof PrototypeConceptIdRoute
  TLibraryRoute: typeof TLibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t': {
      id: '/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof TRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/library': {
      id: '/t_/library'
      path: '/t/library'
      fullPath: '/t/library'
      preLoaderRoute: typeof TLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/$conceptId': {
      id: '/prototype/$conceptId'
      path: '/prototype/$conceptId'
      fullPath: '/prototype/$conceptId'
      preLoaderRoute: typeof PrototypeConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/$handle': {
      id: '/pilot/$handle'
      path: '/pilot/$handle'
      fullPath: '/pilot/$handle'
      preLoaderRoute: typeof PilotHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShowcaseRoute: ShowcaseRoute,
  TRoute: TRoute,
  PilotHandleRoute: PilotHandleRoute,
  PrototypeConceptIdRoute: PrototypeConceptIdRoute,
  TLibraryRoute: TLibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
