/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TRouteImport } from './routes/t'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TShowcaseRouteImport } from './routes/t_.showcase'
import { Route as TLibraryRouteImport } from './routes/t_.library'
import { Route as TFeedbackRouteImport } from './routes/t_.feedback'
import { Route as TCreateRouteImport } from './routes/t_.create'
import { Route as TAdminRouteImport } from './routes/t_.admin'
import { Route as ShowcaseOpengraphImageRouteImport } from './routes/showcase_.opengraph-image'
import { Route as PrototypeConceptIdRouteImport } from './routes/prototype.$conceptId'
import { Route as PilotHandleRouteImport } from './routes/pilot.$handle'
import { Route as CreatorHandleRouteImport } from './routes/creator.$handle'
import { Route as CreatorPackSlugRouteImport } from './routes/creator-pack.$slug'
import { Route as BaseModelSlugStylePresetSlugRouteImport } from './routes/$baseModelSlug.$stylePresetSlug'
import { Route as PrototypeConceptIdOpengraphImageRouteImport } from './routes/prototype_.$conceptId.opengraph-image'
import { Route as PilotHandleOpengraphImageRouteImport } from './routes/pilot_.$handle.opengraph-image'
import { Route as CreatorHandleOpengraphImageRouteImport } from './routes/creator_.$handle.opengraph-image'
import { Route as CreatorPackSlugOpengraphImageRouteImport } from './routes/creator-pack_.$slug.opengraph-image'
import { Route as BaseModelSlugStylePresetSlugOpengraphImageRouteImport } from './routes/$baseModelSlug.$stylePresetSlug.opengraph-image'

const TRoute = TRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TShowcaseRoute = TShowcaseRouteImport.update({
  id: '/t_/showcase',
  path: '/t/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const TLibraryRoute = TLibraryRouteImport.update({
  id: '/t_/library',
  path: '/t/library',
  getParentRoute: () => rootRouteImport,
} as any)
const TFeedbackRoute = TFeedbackRouteImport.update({
  id: '/t_/feedback',
  path: '/t/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const TCreateRoute = TCreateRouteImport.update({
  id: '/t_/create',
  path: '/t/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TAdminRoute = TAdminRouteImport.update({
  id: '/t_/admin',
  path: '/t/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseOpengraphImageRoute = ShowcaseOpengraphImageRouteImport.update({
  id: '/showcase_/opengraph-image',
  path: '/showcase/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeConceptIdRoute = PrototypeConceptIdRouteImport.update({
  id: '/prototype/$conceptId',
  path: '/prototype/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotHandleRoute = PilotHandleRouteImport.update({
  id: '/pilot/$handle',
  path: '/pilot/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHandleRoute = CreatorHandleRouteImport.update({
  id: '/creator/$handle',
  path: '/creator/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPackSlugRoute = CreatorPackSlugRouteImport.update({
  id: '/creator-pack/$slug',
  path: '/creator-pack/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseModelSlugStylePresetSlugRoute =
  BaseModelSlugStylePresetSlugRouteImport.update({
    id: '/$baseModelSlug/$stylePresetSlug',
    path: '/$baseModelSlug/$stylePresetSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrototypeConceptIdOpengraphImageRoute =
  PrototypeConceptIdOpengraphImageRouteImport.update({
    id: '/prototype_/$conceptId/opengraph-image',
    path: '/prototype/$conceptId/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const PilotHandleOpengraphImageRoute =
  PilotHandleOpengraphImageRouteImport.update({
    id: '/pilot_/$handle/opengraph-image',
    path: '/pilot/$handle/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorHandleOpengraphImageRoute =
  CreatorHandleOpengraphImageRouteImport.update({
    id: '/creator_/$handle/opengraph-image',
    path: '/creator/$handle/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorPackSlugOpengraphImageRoute =
  CreatorPackSlugOpengraphImageRouteImport.update({
    id: '/creator-pack_/$slug/opengraph-image',
    path: '/creator-pack/$slug/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const BaseModelSlugStylePresetSlugOpengraphImageRoute =
  BaseModelSlugStylePresetSlugOpengraphImageRouteImport.update({
    id: '/opengraph-image',
    path: '/opengraph-image',
    getParentRoute: () => BaseModelSlugStylePresetSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t': typeof TRoute
  '/$baseModelSlug/$stylePresetSlug': typeof BaseModelSlugStylePresetSlugRouteWithChildren
  '/creator-pack/$slug': typeof CreatorPackSlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/showcase/opengraph-image': typeof ShowcaseOpengraphImageRoute
  '/t/admin': typeof TAdminRoute
  '/t/create': typeof TCreateRoute
  '/t/feedback': typeof TFeedbackRoute
  '/t/library': typeof TLibraryRoute
  '/t/showcase': typeof TShowcaseRoute
  '/$baseModelSlug/$stylePresetSlug/opengraph-image': typeof BaseModelSlugStylePresetSlugOpengraphImageRoute
  '/creator-pack/$slug/opengraph-image': typeof CreatorPackSlugOpengraphImageRoute
  '/creator/$handle/opengraph-image': typeof CreatorHandleOpengraphImageRoute
  '/pilot/$handle/opengraph-image': typeof PilotHandleOpengraphImageRoute
  '/prototype/$conceptId/opengraph-image': typeof PrototypeConceptIdOpengraphImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t': typeof TRoute
  '/$baseModelSlug/$stylePresetSlug': typeof BaseModelSlugStylePresetSlugRouteWithChildren
  '/creator-pack/$slug': typeof CreatorPackSlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/showcase/opengraph-image': typeof ShowcaseOpengraphImageRoute
  '/t/admin': typeof TAdminRoute
  '/t/create': typeof TCreateRoute
  '/t/feedback': typeof TFeedbackRoute
  '/t/library': typeof TLibraryRoute
  '/t/showcase': typeof TShowcaseRoute
  '/$baseModelSlug/$stylePresetSlug/opengraph-image': typeof BaseModelSlugStylePresetSlugOpengraphImageRoute
  '/creator-pack/$slug/opengraph-image': typeof CreatorPackSlugOpengraphImageRoute
  '/creator/$handle/opengraph-image': typeof CreatorHandleOpengraphImageRoute
  '/pilot/$handle/opengraph-image': typeof PilotHandleOpengraphImageRoute
  '/prototype/$conceptId/opengraph-image': typeof PrototypeConceptIdOpengraphImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t': typeof TRoute
  '/$baseModelSlug/$stylePresetSlug': typeof BaseModelSlugStylePresetSlugRouteWithChildren
  '/creator-pack/$slug': typeof CreatorPackSlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/pilot/$handle': typeof PilotHandleRoute
  '/prototype/$conceptId': typeof PrototypeConceptIdRoute
  '/showcase_/opengraph-image': typeof ShowcaseOpengraphImageRoute
  '/t_/admin': typeof TAdminRoute
  '/t_/create': typeof TCreateRoute
  '/t_/feedback': typeof TFeedbackRoute
  '/t_/library': typeof TLibraryRoute
  '/t_/showcase': typeof TShowcaseRoute
  '/$baseModelSlug/$stylePresetSlug/opengraph-image': typeof BaseModelSlugStylePresetSlugOpengraphImageRoute
  '/creator-pack_/$slug/opengraph-image': typeof CreatorPackSlugOpengraphImageRoute
  '/creator_/$handle/opengraph-image': typeof CreatorHandleOpengraphImageRoute
  '/pilot_/$handle/opengraph-image': typeof PilotHandleOpengraphImageRoute
  '/prototype_/$conceptId/opengraph-image': typeof PrototypeConceptIdOpengraphImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/showcase'
    | '/sitemap.xml'
    | '/t'
    | '/$baseModelSlug/$stylePresetSlug'
    | '/creator-pack/$slug'
    | '/creator/$handle'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/showcase/opengraph-image'
    | '/t/admin'
    | '/t/create'
    | '/t/feedback'
    | '/t/library'
    | '/t/showcase'
    | '/$baseModelSlug/$stylePresetSlug/opengraph-image'
    | '/creator-pack/$slug/opengraph-image'
    | '/creator/$handle/opengraph-image'
    | '/pilot/$handle/opengraph-image'
    | '/prototype/$conceptId/opengraph-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/showcase'
    | '/sitemap.xml'
    | '/t'
    | '/$baseModelSlug/$stylePresetSlug'
    | '/creator-pack/$slug'
    | '/creator/$handle'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/showcase/opengraph-image'
    | '/t/admin'
    | '/t/create'
    | '/t/feedback'
    | '/t/library'
    | '/t/showcase'
    | '/$baseModelSlug/$stylePresetSlug/opengraph-image'
    | '/creator-pack/$slug/opengraph-image'
    | '/creator/$handle/opengraph-image'
    | '/pilot/$handle/opengraph-image'
    | '/prototype/$conceptId/opengraph-image'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/showcase'
    | '/sitemap.xml'
    | '/t'
    | '/$baseModelSlug/$stylePresetSlug'
    | '/creator-pack/$slug'
    | '/creator/$handle'
    | '/pilot/$handle'
    | '/prototype/$conceptId'
    | '/showcase_/opengraph-image'
    | '/t_/admin'
    | '/t_/create'
    | '/t_/feedback'
    | '/t_/library'
    | '/t_/showcase'
    | '/$baseModelSlug/$stylePresetSlug/opengraph-image'
    | '/creator-pack_/$slug/opengraph-image'
    | '/creator_/$handle/opengraph-image'
    | '/pilot_/$handle/opengraph-image'
    | '/prototype_/$conceptId/opengraph-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TRoute: typeof TRoute
  BaseModelSlugStylePresetSlugRoute: typeof BaseModelSlugStylePresetSlugRouteWithChildren
  CreatorPackSlugRoute: typeof CreatorPackSlugRoute
  CreatorHandleRoute: typeof CreatorHandleRoute
  PilotHandleRoute: typeof PilotHandleRoute
  PrototypeConceptIdRoute: typeof PrototypeConceptIdRoute
  ShowcaseOpengraphImageRoute: typeof ShowcaseOpengraphImageRoute
  TAdminRoute: typeof TAdminRoute
  TCreateRoute: typeof TCreateRoute
  TFeedbackRoute: typeof TFeedbackRoute
  TLibraryRoute: typeof TLibraryRoute
  TShowcaseRoute: typeof TShowcaseRoute
  CreatorPackSlugOpengraphImageRoute: typeof CreatorPackSlugOpengraphImageRoute
  CreatorHandleOpengraphImageRoute: typeof CreatorHandleOpengraphImageRoute
  PilotHandleOpengraphImageRoute: typeof PilotHandleOpengraphImageRoute
  PrototypeConceptIdOpengraphImageRoute: typeof PrototypeConceptIdOpengraphImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t': {
      id: '/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof TRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/showcase': {
      id: '/t_/showcase'
      path: '/t/showcase'
      fullPath: '/t/showcase'
      preLoaderRoute: typeof TShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/library': {
      id: '/t_/library'
      path: '/t/library'
      fullPath: '/t/library'
      preLoaderRoute: typeof TLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/feedback': {
      id: '/t_/feedback'
      path: '/t/feedback'
      fullPath: '/t/feedback'
      preLoaderRoute: typeof TFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/create': {
      id: '/t_/create'
      path: '/t/create'
      fullPath: '/t/create'
      preLoaderRoute: typeof TCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/admin': {
      id: '/t_/admin'
      path: '/t/admin'
      fullPath: '/t/admin'
      preLoaderRoute: typeof TAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase_/opengraph-image': {
      id: '/showcase_/opengraph-image'
      path: '/showcase/opengraph-image'
      fullPath: '/showcase/opengraph-image'
      preLoaderRoute: typeof ShowcaseOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/$conceptId': {
      id: '/prototype/$conceptId'
      path: '/prototype/$conceptId'
      fullPath: '/prototype/$conceptId'
      preLoaderRoute: typeof PrototypeConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/$handle': {
      id: '/pilot/$handle'
      path: '/pilot/$handle'
      fullPath: '/pilot/$handle'
      preLoaderRoute: typeof PilotHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$handle': {
      id: '/creator/$handle'
      path: '/creator/$handle'
      fullPath: '/creator/$handle'
      preLoaderRoute: typeof CreatorHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-pack/$slug': {
      id: '/creator-pack/$slug'
      path: '/creator-pack/$slug'
      fullPath: '/creator-pack/$slug'
      preLoaderRoute: typeof CreatorPackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$baseModelSlug/$stylePresetSlug': {
      id: '/$baseModelSlug/$stylePresetSlug'
      path: '/$baseModelSlug/$stylePresetSlug'
      fullPath: '/$baseModelSlug/$stylePresetSlug'
      preLoaderRoute: typeof BaseModelSlugStylePresetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype_/$conceptId/opengraph-image': {
      id: '/prototype_/$conceptId/opengraph-image'
      path: '/prototype/$conceptId/opengraph-image'
      fullPath: '/prototype/$conceptId/opengraph-image'
      preLoaderRoute: typeof PrototypeConceptIdOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot_/$handle/opengraph-image': {
      id: '/pilot_/$handle/opengraph-image'
      path: '/pilot/$handle/opengraph-image'
      fullPath: '/pilot/$handle/opengraph-image'
      preLoaderRoute: typeof PilotHandleOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator_/$handle/opengraph-image': {
      id: '/creator_/$handle/opengraph-image'
      path: '/creator/$handle/opengraph-image'
      fullPath: '/creator/$handle/opengraph-image'
      preLoaderRoute: typeof CreatorHandleOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-pack_/$slug/opengraph-image': {
      id: '/creator-pack_/$slug/opengraph-image'
      path: '/creator-pack/$slug/opengraph-image'
      fullPath: '/creator-pack/$slug/opengraph-image'
      preLoaderRoute: typeof CreatorPackSlugOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$baseModelSlug/$stylePresetSlug/opengraph-image': {
      id: '/$baseModelSlug/$stylePresetSlug/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/$baseModelSlug/$stylePresetSlug/opengraph-image'
      preLoaderRoute: typeof BaseModelSlugStylePresetSlugOpengraphImageRouteImport
      parentRoute: typeof BaseModelSlugStylePresetSlugRoute
    }
  }
}

interface BaseModelSlugStylePresetSlugRouteChildren {
  BaseModelSlugStylePresetSlugOpengraphImageRoute: typeof BaseModelSlugStylePresetSlugOpengraphImageRoute
}

const BaseModelSlugStylePresetSlugRouteChildren: BaseModelSlugStylePresetSlugRouteChildren =
  {
    BaseModelSlugStylePresetSlugOpengraphImageRoute:
      BaseModelSlugStylePresetSlugOpengraphImageRoute,
  }

const BaseModelSlugStylePresetSlugRouteWithChildren =
  BaseModelSlugStylePresetSlugRoute._addFileChildren(
    BaseModelSlugStylePresetSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShowcaseRoute: ShowcaseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TRoute: TRoute,
  BaseModelSlugStylePresetSlugRoute:
    BaseModelSlugStylePresetSlugRouteWithChildren,
  CreatorPackSlugRoute: CreatorPackSlugRoute,
  CreatorHandleRoute: CreatorHandleRoute,
  PilotHandleRoute: PilotHandleRoute,
  PrototypeConceptIdRoute: PrototypeConceptIdRoute,
  ShowcaseOpengraphImageRoute: ShowcaseOpengraphImageRoute,
  TAdminRoute: TAdminRoute,
  TCreateRoute: TCreateRoute,
  TFeedbackRoute: TFeedbackRoute,
  TLibraryRoute: TLibraryRoute,
  TShowcaseRoute: TShowcaseRoute,
  CreatorPackSlugOpengraphImageRoute: CreatorPackSlugOpengraphImageRoute,
  CreatorHandleOpengraphImageRoute: CreatorHandleOpengraphImageRoute,
  PilotHandleOpengraphImageRoute: PilotHandleOpengraphImageRoute,
  PrototypeConceptIdOpengraphImageRoute: PrototypeConceptIdOpengraphImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
